version: "3.4"

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: postgresdb
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  api:
    image: node:16-alpine3.11
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DATABASE_URL: "postgres://root:password@db:5432/app"
    volumes:
      - .:/home/node/app
    depends_on:
      - postgres
    working_dir: /home/node/app
    command: sh -c "npm install --no-update-notifier; npm start --no-update-notifier"


volumes:
  db-data: {}
